### ISSUE TITLE
FEAT: Ability to control tile map wrapping

### ISSUE THREAD

**Issue by jsbnr** [newrelic-experimental/nr1-viz-geo-location#8]
At the moment when you zoom out the world map wraps infinitiely. Would like the option to display the map only once.

**Comment by jsbnr** [comment]
The `<TileMap noWrap>` attribute should help here.

**Comment by matewilk** [comment]
Ready once PR https://github.com/newrelic-experimental/nr1-viz-geo-location/pull/7 is merged

**Comment by jsbnr** [comment]
Merged to main
